pod 'libqrencode', '~> 3.4.2'
pod 'MarqueeLabel', '~> 2.0.5'
pod 'SDWebImage', '~> 3.7.1'
pod 'JSONModel'
pod 'AFNetworking', '~> 2.3'
pod 'SVProgressHUD', '~> 1.0'
pod 'RBStoryboardLink', '~> 0.1.0'
